[package]
name = "yellowstone-grpc-client"
version = "10.2.0+solana.3.0.14"
authors = { workspace = true }
edition = { workspace = true }
description = "Yellowstone gRPC Geyser Simple Client"
homepage = { workspace = true }
repository = { workspace = true }
license = "Apache-2.0"
keywords = { workspace = true }
publish = true

[features]
account-data-as-bytes = [
    "yellowstone-grpc-proto/account-data-as-bytes"
]

[dependencies]
bytes = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true, features = ["tls-native-roots"] }
tonic-health = { workspace = true }

# Yellowstone
yellowstone-grpc-proto = { workspace = true, features = ["tonic", "tonic-compression"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
