[package]
name = "yellowstone-grpc-client"
version = "11.0.1"
authors = { workspace = true }
edition = { workspace = true }
description = "Yellowstone gRPC Geyser Simple Client"
homepage = { workspace = true }
repository = { workspace = true }
license = "Apache-2.0"
keywords = { workspace = true }
publish = true

[features]
default = []
account-data-as-bytes = [
    "yellowstone-grpc-proto/account-data-as-bytes"
]
opentelemetry = [
    "dep:opentelemetry",
    "dep:opentelemetry_sdk",
    "dep:tracing",
]

[dependencies]
bytes = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true, features = ["tls-native-roots"] }
tonic-health = { workspace = true }

# Yellowstone
yellowstone-grpc-proto = { workspace = true, features = ["tonic", "tonic-compression"] }

# OpenTelemetry (optional)
opentelemetry = { workspace = true, optional = true }
opentelemetry_sdk = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
