[package]
name = "yellowstone-grpc-proto"
version = "2.0.0"
authors = { workspace = true }
edition = { workspace = true }
description = "Yellowstone gRPC Geyser Protobuf Definitions"
homepage = { workspace = true }
repository = { workspace = true }
license = "Apache-2.0"
keywords = { workspace = true }
publish = true

[dependencies]
bincode = { workspace = true }
prost = { workspace = true }
solana-account-decoder = { workspace = true, optional = true }
solana-sdk = { workspace = true, optional = true }
solana-transaction-status = { workspace = true, optional = true }
tonic = { workspace = true }
yellowstone-grpc-geyser-messages = { workspace = true, optional = true }

[build-dependencies]
anyhow = { workspace = true }
protobuf-src = { workspace = true }
tonic-build = { workspace = true }

[features]
convert = ["dep:solana-account-decoder", "dep:solana-sdk", "dep:solana-transaction-status"]
geyser_weak = ["dep:yellowstone-grpc-geyser-messages"]
tonic-compression = ["tonic/gzip", "tonic/zstd"]
default = ["convert", "tonic-compression"]

[lints]
workspace = true
