[package]
name = "yellowstone-grpc-client-simple"
version = "1.1.0+solana.1.14.17"
authors = ["Triton One"]
edition = "2021"
publish = false

[[bin]]
name = "client"

[dependencies]
anyhow = "1.0.62"
backoff = { version = "0.4.0", features = ["tokio"] }
bs58 = "0.4.0"
clap = { version = "3.2.23", features = ["cargo", "derive"] }
env_logger = "0.10.0"
futures = "0.3.24"
hex = "0.4.3"
log = { version = "0.4.14", features = ["std"] }
solana-sdk = "=1.14.17"
tokio = { version = "1.21.2", features = ["rt-multi-thread", "macros", "time"] }
yellowstone-grpc-client = { path = "../../yellowstone-grpc-client" }
yellowstone-grpc-proto = { path = "../../yellowstone-grpc-proto" }
